server = "http://localhost:8888"

[Login]
email = 
password = 

[Logging]
default = "Debug"

[[Dir]]
path = "content/blog"
filter = "end:.md"
type = "content"

# [[Dir]]
# path = "content/media"
# type = "media"